In [1]:
import urllib
import requests 
from bs4 import BeautifulSoup
import json

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service 
import pyperclip

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.io.json import json_normalize

In [4]:
import time
import warnings
warnings.filterwarnings(action='ignore')
from IPython.display import Image

In [5]:
pwd

'C:\\Users\\snm03\\Documents\\debbu\\gameData\\the_log'

In [10]:


df = pd.read_csv('C:/Users/snm03/Documents/debbu/gameData/the_log_csv/pc_201801_1.csv')
df

,tablescraper-selected-row,name,name href,tablescraper-selected-row 2,tablescraper-selected-row 3,tablescraper-selected-row 4,num,num 2,num 3,num 4,tablescraper-selected-row 5,tablescraper-selected-row 6,on,on href,intop_btnarea
0,1.0,배틀그라운드,javascript:void(0);,FPS,70.89,36.75,"9,407","11,407,612",92.0,"7,464,234",카카오/스팀,유료,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,점유율 등락,javascript:void(0);,이용시간 등락
2,2.0,리그 오브 레전드,javascript:void(0);,RTS,86.69,22.35,"9,524","6,938,099",94.0,"4,448,793",라이엇게임즈,유료,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,점유율 등락,javascript:void(0);,이용시간 등락
4,3.0,오버워치,javascript:void(0);,FPS,19.23,9.97,"9,430","3,094,425",74.0,"2,521,406",블리자드,유료,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,점유율 등락,javascript:void(0);,이용시간 등락
480,241.0,라키온,javascript:void(0);,RPG,0.01,0.01,2,1,24.0,2,CJ인터넷,무료,NaN,NaN,NaN
481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,점유율 등락,javascript:void(0);,이용시간 등락
482,242.0,네임드,javascript:void(0);,RPG,0.01,0.01,0,1,3.0,2,녹스,유료,NaN,NaN,NaN
483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,점유율 등락,javascript:void(0);,이용시간 등락

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   tablescraper-selected-row    242 non-null    float64
 1   name                         242 non-null    object
 2   name href                    242 non-null    object
 3   tablescraper-selected-row 2  242 non-null    object
 4   tablescraper-selected-row 3  242 non-null    float64
 5   tablescraper-selected-row 4  242 non-null    float64
 6   num                          242 non-null    object
 7   num 2                        242 non-null    object
 8   num 3                        242 non-null    float64
 9   num 4                        242 non-null    object
 10  tablescraper-selected-row 5  242 non-null    object
 11  tablescraper-selected-row 6  241 non-null    object
 12  on                           242 non-null    object
 13  on href                      242 non-null    object
 14  intop_btnarea                242 non-null    object
dtypes: float64(4), object(11)
memory usage: 56.8+ KB

In [12]:
df.iloc[::2]

,tablescraper-selected-row,name,name href,tablescraper-selected-row 2,tablescraper-selected-row 3,tablescraper-selected-row 4,num,num 2,num 3,num 4,tablescraper-selected-row 5,tablescraper-selected-row 6,on,on href,intop_btnarea
0,1.0,배틀그라운드,javascript:void(0);,FPS,70.89,36.75,"9,407","11,407,612",92.0,"7,464,234",카카오/스팀,유료,NaN,NaN,NaN
2,2.0,리그 오브 레전드,javascript:void(0);,RTS,86.69,22.35,"9,524","6,938,099",94.0,"4,448,793",라이엇게임즈,유료,NaN,NaN,NaN
4,3.0,오버워치,javascript:void(0);,FPS,19.23,9.97,"9,430","3,094,425",74.0,"2,521,406",블리자드,유료,NaN,NaN,NaN
6,4.0,서든어택,javascript:void(0);,FPS,8.31,4.31,"9,326","1,335,868",68.0,"1,182,326",넥슨,유료,NaN,NaN,NaN
8,5.0,던전앤파이터,javascript:void(0);,액션,70.33,2.64,"8,899","816,895",83.0,"580,764",넥슨,유료,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,238.0,넷마블 로우바둑이,javascript:void(0);,보드,0.01,0.01,0,4,46.0,2,넷마블,무료,NaN,NaN,NaN
476,239.0,온라인 삼국지,javascript:void(0);,RPG,0.01,0.01,1,2,16.0,4,(주)코스모스엔터테인먼트,무료,NaN,NaN,NaN
478,240.0,네이비필드2,javascript:void(0);,RTS,0.01,0.01,1,2,26.0,2,에스디엔터넷,유료,NaN,NaN,NaN
480,241.0,라키온,javascript:void(0);,RPG,0.01,0.01,2,1,24.0,2,CJ인터넷,무료,NaN,NaN,NaN
482,242.0,네임드,javascript:void(0);,RPG,0.01,0.01,0,1,3.0,2,녹스,유료,NaN,NaN,NaN

In [17]:
df2=df.loc[:, ['tablescraper-selected-row',
               'name',
               'tablescraper-selected-row 2',
               'tablescraper-selected-row 3',
               'num',
               'num 2',
               'num 3',
               'num 4',
               'tablescraper-selected-row 5']]
df2.iloc[::2][:40]

,tablescraper-selected-row,name,tablescraper-selected-row 2,tablescraper-selected-row 3,num,num 2,num 3,num 4,tablescraper-selected-row 5
0,1.0,배틀그라운드,FPS,70.89,"9,407","11,407,612",92.0,"7,464,234",카카오/스팀
2,2.0,리그 오브 레전드,RTS,86.69,"9,524","6,938,099",94.0,"4,448,793",라이엇게임즈
4,3.0,오버워치,FPS,19.23,"9,430","3,094,425",74.0,"2,521,406",블리자드
6,4.0,서든어택,FPS,8.31,"9,326","1,335,868",68.0,"1,182,326",넥슨
8,5.0,던전앤파이터,액션,70.33,"8,899","816,895",83.0,"580,764",넥슨
10,6.0,스타크래프트 리마스터,RTS,8.95,"9,086","716,051",70.0,"617,973",블리자드
12,7.0,메이플스토리,RPG,22.76,"8,743","661,255",83.0,"482,497",넥슨
14,8.0,리니지,RPG,11.51,"5,730","334,189",121.0,"165,683",엔씨소프트
16,9.0,월드 오브 워크래프트,RPG,9.55,"5,726","277,312",127.0,"131,808",블리자드
18,10.0,디아블로3,RPG,9.36,"6,478","271,875",114.0,"144,391",블리자드
20,11.0,블레이드 & 소울,RPG,7.59,"5,452","220,442",107.0,"123,541",엔씨소프트
22,12.0,검은사막,RPG,6.95,"5,484","201,885",106.0,"116,272",(주)펄어비스
24,13.0,카트라이더,레이싱,60.18,"7,862","176,532",37.0,"291,409",넥슨
26,14.0,사이퍼즈,액션,14.94,"5,097","173,511",112.0,"92,762",넥슨
28,15.0,워크래프트3 리포지드,RTS,1.60,"3,982","127,909",83.0,"92,691",블리자드
30,16.0,아이온,RPG,4.17,"3,742","120,948",100.0,"73,014",엔씨소프트
32,17.0,히어로즈 오브 더 스톰,RTS,1.26,"3,208","100,505",86.0,"70,605",블리자드
34,18.0,테라,RPG,3.06,"2,858","88,766",97.0,"54,948",넥슨
36,19.0,테일즈런너,스포츠,4.53,"4,974","85,679",44.0,"118,644",스마일게이트
38,20.0,파이널판타지14,RPG,2.66,"2,358","77,104",151.0,"30,771",액토즈소프트
40,21.0,GTA 5,액션,6.57,"2,402","76,210",74.0,"61,924",스팀
42,22.0,한게임 로우바둑이,보드,14.53,"3,552","72,773",27.0,"164,514",한게임
44,23.0,엘소드,RPG,2.47,"3,802","71,599",68.0,"63,000",넥슨
46,24.0,크레이지아케이드,아케이드,64.94,"5,160","71,178",30.0,"146,174",넥슨
48,25.0,스페셜포스,FPS,0.44,"2,741","69,702",99.0,"42,310",네오위즈
50,26.0,스타크래프트2,RTS,0.85,"3,065","67,270",76.0,"53,607",블리자드
52,27.0,하스스톤,보드,12.67,"5,011","63,429",43.0,"90,331",블리자드
54,28.0,카운터-스트라이크 온라인,FPS,0.39,"5,064","62,132",34.0,"112,365",넥슨
56,29.0,클로저스,액션,4.77,"3,120","55,314",72.0,"46,200",넥슨
58,30.0,리니지2,RPG,1.63,"1,763","47,231",148.0,"19,211",엔씨소프트
60,31.0,거상,RPG,1.47,"1,830","42,617",89.0,"28,374",(주)에이케이인터렉티브
62,32.0,버블파이터,슈팅,79.97,"3,018","40,468",50.0,"48,920",넥슨
64,33.0,한게임 신맞고,보드,7.61,"2,976","38,110",40.0,"58,180",한게임
66,34.0,마비노기 영웅전,RPG,1.25,"1,995","36,207",87.0,"25,151",넥슨
68,35.0,아키에이지,RPG,1.23,"1,234","35,672",59.0,"35,024",넥슨
70,36.0,한게임 하이로우,보드,6.97,"2,396","34,873",24.0,"90,340",한게임
72,37.0,DOTA 2,RTS,0.44,800,"34,696",128.0,"16,384",스팀
74,38.0,아바,FPS,0.22,"1,976","34,344",65.0,"32,395",네오위즈
76,39.0,라그나로크 Zero,RPG,1.18,"1,156","34,063",123.0,"16,530",그라비티
78,40.0,프리스타일2,스포츠,1.71,"2,229","32,302",63.0,"30,781",넥슨